### ISSUE TITLE
Deathgrip not working as expected

### ISSUE THREAD

**Issue by skiunke** [TTT-2/ttt2-deathgrip#4]
Collection link: https://steamcommunity.com/sharedfiles/filedetails/?id=2038664244
(Collection inherits from: https://steamcommunity.com/sharedfiles/filedetails/?id=2038642900)

Situation: Deathgrip addon not working as expected
Problem: Connected player to deathgrip does not die on death
Occurs if: always
Detailed: System prints, that a couple has been selected, but the death penalty never executes. Missing text result and death of character. 

Video: https://youtu.be/9BHRZonRFbM

**Comment by Histalek** [comment]
https://github.com/TTT-2/ttt2-deathgrip/blob/dcc08e956301740c86a52f2d829b9e745aceecfc/lua/autorun/server/sv_deathgrip_handler.lua#L75

i would reckon the problem lies in that if-condition. @TimGoll would you take a look at it?

**Comment by TimGoll** [comment]
Yes, I think it is that line. That makes no sense to me

**Comment by Histalek** [comment]
Should be fixed as of the latest commit. The Workshopversion will be updated accordingly, i can't give an estimate on when though.

Thank you for reporting :)
