### ISSUE TITLE
Deathgrip convars not working

### ISSUE THREAD

**Issue by Pustekuchen98** [TTT-2/ttt2-deathgrip#6]
## Your version of TTT2 (mandatory)

- Workshop version from Steam
  TTT2 (Base) - v0.6.4b

## Describe the bug (mandatory)

Convars of the deathgrip role are not working at all. Namely "ttt2_deathgrip_chance" and
"ttt2_deathgrip_reset_min_players".

## Expected behaviour

Changing the deathgrip spawn chance + the minimum player count for the deathgrip to be removed.

## Context (please provide as much as you can)

- Collection link of your Server: https://steamcommunity.com/sharedfiles/filedetails/?id=2058297637
- **All** Server errors in the server console
- Client errors in the developer console
- Other addons installed in your servers `addons` folder: none
- Screenshots

**Comment by tomatosoupcan** [comment]
Is this because math.random(0,1) will only return 0 or 1? Going to test that myself tonight.

**Comment by tomatosoupcan** [comment]
Update: yes, I tested this myself. Should be using math.random(0,100)/100 instead, or simply math.random() I believe.

**Comment by Pustekuchen98** [comment]
The issue you are talking about was fixed with the last commit about 1 month ago. I just couldn't close the issue because the problem with the 'min player deathgrip' reset still exists.

**Comment by TimGoll** [comment]
I have some time right now, I'll test it

**Comment by TimGoll** [comment]
fixed in dev

**Comment by tomatosoupcan** [comment]
As far as I can tell, math.random(0,1) will still always return a full integer value of 0 or 1, making the odds remain 50/50. Maybe my gmod executes this code differently than others somehow. I was logging the output to chat last night and restarting the round and never saw anything other than 0 or 1 come up.

**Comment by TimGoll** [comment]
Pustekuchen said that it was fixed so I did not bother checking it

**Comment by TimGoll** [comment]
I changed it to `math.Rand`, it should work now

**Comment by Pustekuchen98** [comment]
It did work on my server after my commit. So thats why I said it is fixed. And I never experienced 50/50 odds after that. That is strange.
